### ISSUE TITLE
Templating fails with Multi-Value option

### ISSUE THREAD

**Issue by mathias-muench** [sni/grafana-pnp-datasource#10]
Hi!

I introduced a template variable (Type Custom) with three values.  Everything is fine when using the variable as single select.

When I try to introduce a dashboard with panel repeat, I change the variable to option "Multi-Value".  Now the panel is repeated three times, but no data points are shown any more.

May be due to the necessary plugin hint for formating multiple values?

PNP v1.0.3, Grafana v4.4.3

Best regards, Mathias

**Comment by sni** [comment]
Its quite likely that this won't work yet, i never tried custom templates so far :-)
I will have a look.

**Comment by sni** [comment]
Should work with the latest 1.0.4 release now. Thanks

**Comment by mathias-muench** [comment]
Just tested, works perfect.  Thank you!
