### ISSUE TITLE
HTTP Error Internal Server Error

### ISSUE THREAD

**Issue by gmourani** [sni/grafana-pnp-datasource#11]
Hello,

The datasource part doesn't seem to work either with Proxy or direct connection. I always receive a HTTP Error Internal Server Error response when clicking on 'Save'.

Grafana: 4.4.3
pnp4nagios: 0.6.25
nagios: 4.3.2

Regards,

**Comment by sni** [comment]
Well, thats not much to work with. Are there any details in grafana or maybe in firebug/chrome devtools?

**Comment by gmourani** [comment]
I've found the problem to be related to the pnp4nagios folder permission. Apache need to have access to the controllers folder for the datasource to work.

Now I'm trying to implement Templating as explained on the README but doesn't seem to work. Fields are available and I can select host or service ou label but the graphs don't change or adjust to reflect the choice.

**Comment by sni** [comment]
Sounds like you did not use the variable in the query editor. You need set the Host to /$HOST$/ or something like that. The autocomplete list should contain an entry for all defined variables.

**Comment by gmourani** [comment]
I've used the following as described on the README.

$host host
$service services where host = /^$host$/
$label labels where host = /^$host$/ and service = /^$service$/

> The autocomplete list should contain an entry for all defined variables.
It contains the entries, but when I select something (host,service), the corresponding graph doesn't change.

**Comment by sni** [comment]
Right, but you need to use the variables in the query too. Something like this:


<img width="524" alt="pnp" src="https://user-images.githubusercontent.com/150844/30416125-44672cca-992b-11e7-8372-0d95c3dfbd3b.png">

**Comment by gmourani** [comment]
Thanks Sven, I understand now, It works.

**Comment by sni** [comment]
You are welcome. Feel free to extend the readme
