### ISSUE TITLE
Version 1.0.3 Templating doesn't work with Grafana 4.5.1

### ISSUE THREAD

**Issue by gmourani** [sni/grafana-pnp-datasource#12]
Hello,

With latest Grafana 4.5.1, templating return error as shown on the attached screenshot. Were working with Grafana 4.4.3.

<img width="1659" alt="screen shot 2017-09-18 at 1 47 49 pm" src="https://user-images.githubusercontent.com/20328799/30557505-8b17b4a6-9c7c-11e7-8c31-977eadfe90d5.png">

**Comment by sni** [comment]
fixed in the latest 1.0.4 release. Thanks
