### ISSUE TITLE
data source does not apply

### ISSUE THREAD

**Issue by welj** [sni/grafana-pnp-datasource#13]
Grafana is last, PNP plugin 1.0.4, pnp4nagios 0.6.22 , nagios (FAN) 3.4.4

I cant add new data source with PNP , error is empty.

https://imgur.com/a/OKdjL

**Comment by sni** [comment]
Have you installed the pnp api like the readme describes?

**Comment by welj** [comment]
Yes, added api.php but nothing

**Comment by welj** [comment]
if I enter any other address where there is a web part, I get the same error
