### ISSUE TITLE
Feature request - Hostgroups

### ISSUE THREAD

**Issue by krutaw** [sni/grafana-pnp-datasource#14]
Fantastic plugin for Grafana, seriously.  The only thing I'd love to see added is support for graphing based on hostgroups instead of hosts.  This would allow for building dashboards that are self-maintaining based on Nagios itself rather than having to update the dashboard every time you add/remove a host host from Nagios.

**Comment by sni** [comment]
That would be nice indeed, but hostgroup information is not available in that context.
