### ISSUE TITLE
No services listed under host in query editor when running v1.0.4 

### ISSUE THREAD

**Issue by pierrewulff** [sni/grafana-pnp-datasource#15]
After upgrade to v1.0.4 the service lists for the hosts is empty.
Queries in graphs created earlier still works as expected, but when trying to change the service on these queries, they show the same issue as on new ones, not listing the services. 

Downgrading to v1.0.3 solved the problem.
Running Grafana v4.5.2

**Comment by welj** [comment]
Yes, i have some problems. Pls fix it.

**Comment by sni** [comment]
Latest commit should fix the issue. You can verify this by manually downloading the plugin following the steps from the readme.

**Comment by pierrewulff** [comment]
Have verified that the latest commit fixes the issue.
Thank you.

**Comment by sni** [comment]
Thanks for testing.
