### ISSUE TITLE
'Label' dropdown returns all services, not just for one being filtered on

### ISSUE THREAD

**Issue by sherl0k** [sni/grafana-pnp-datasource#16]
When selecting a label for a service, it wildcards to all the services, from all hosts, rather than using the Host and Service that I selected in the dropdowns preceding Label. The Query Inspector shows this:

`xhrStatus:"complete"
request:Object
method:"POST"
url:"api/datasources/proxy/2/index.php/api/labels/"
data:Object
host:"/.*/"
service:"/.*/"
response:Object
labels:Array[275]`

Using Grafana 4.6.2 and the latest version of the plugin in the grafana repos.

**Comment by sni** [comment]
I just pushed a pull request with the latest 1.0.5 version of the datasource to the grafana repo. This should fix this issue.

**Comment by sherl0k** [comment]
Cloned from this repo and confirmed it's working as designed. Thanks! Hopefully the grafana devs update the plugin on their end soon.
