### ISSUE TITLE
Grafana complains about duplicate id because of dist/src/plugin.json

### ISSUE THREAD

**Issue by kompa3** [sni/grafana-pnp-datasource#17]
This plugin seems to have an identical problem to the one suffered once by JSON datasource:  https://github.com/grafana/simple-json-datasource/issues/38

At Grafana restart, it complains
```
Jan 10 09:00:54 localhost grafana-xxl[971]: t=2018-01-10T09:00:54+0000 lvl=eror msg="Plugins: Failed to load plugin json file: /grafana-plugins/sni-pnp-datasource/dist/src/plugin.json,  err: Plugin with same id already exists"
```

The solution is straightforward and probably identical to https://github.com/grafana/simple-json-datasource/commit/b4d955245aedb9a4243733626a715dfc58d9a694, ie. removing dist/src from Gruntfile.

**Comment by sni** [comment]
should be better now, thanks
