### ISSUE TITLE
multiple labels uses same data

### ISSUE THREAD

**Issue by facenn** [sni/grafana-pnp-datasource#18]
First of all, thanks for this plugin. 

We facing one problem when we try to create a graph for disk usage.

![grafana_label](https://user-images.githubusercontent.com/27153878/35149224-971ee05e-fd15-11e7-9fe3-a3b18b27706c.png)

As shown in the picture above you can see that we select different labels, but the data values remains the same. 

Our perfdata looks like this:

/=2123MB;4343;4599;0;5110 /dev=0MB;1599;1693;0;1882 /run=200MB;1609;1703;0;1893 /sys/fs/cgroup=0MB;1609;1703;0;1893 /boot=232MB;336;356;0;396 /var=7179MB;17399;18423;0;20470 /tmp=32MB;1732;1834;0;2038 /home=1158MB;4348;4604;0;5116 /var/lib/mysql=1477MB;8695;9207;0;10230 /home/perconabackup=1183MB;8695;9207;0;10230 /var/www=61896MB;87031;92151;0;102390

Is there something wrong with the format of our perfdata?

Best regards

facenn

**Comment by sni** [comment]
Which version is that? I thought this has been fixed meanwhile.

**Comment by facenn** [comment]
Hi,

sni-pnp-datasource @ 1.0.5
Grafana v4.6.3

**Comment by sni** [comment]
I cannot reproduce that, could make sure you are using the latest pnp api.php?

**Comment by facenn** [comment]
My fault... latest pnp api.php solved the issue. 

Thanks for your fast response!
