### ISSUE TITLE
No Datapoints in Graph with multiple Queries if first Query has none

### ISSUE THREAD

**Issue by JohannesEbke** [sni/grafana-pnp-datasource#19]
If the first Query in a Graph with multiple Queries returns no data points, the plot shows "no data points", even if subsequent queries return data.

My use case is a graph in a templated dashboard, where i've got a set of queries configured which may not all be defined for a host.

I suspect that the response data may not be correctly parsed on the Grafana side. If I configure two queries (one empty and one not) and look at the query inspector, i see:

Empty one last:
`response: Object { targets: Array[1]: [0: Array[1]: [0: Object: {...}]]}`
Empty one first:
`response: Object { targets: Object: {1: Array[1]: [0: Object: {...}]}}`

**Comment by sni** [comment]
This is an issue in the pnp api itself, should be fixed with:
https://github.com/lingej/pnp-metrics-api/pull/11
