### ISSUE TITLE
Multi-Value Template Variable not correctly set in Alias

### ISSUE THREAD

**Issue by JohannesEbke** [sni/grafana-pnp-datasource#20]
If I use a multi-value template variable $host in a Query Alias (set to host1, host2 and host3), the string in the label of every time series is "{host1,host2,host3}", and not "host1" for the time series corresponding to host1, etc.

As is, I cannot distinguish between hosts in the time series.

**Comment by sni** [comment]
Sorry for not responding earlier. I just tried and cannot reproduce this issue. Please double check to use `/^$host$/` in your query.
