### ISSUE TITLE
Can't connect to pnp4nagios - empty alert-body 

### ISSUE THREAD

**Issue by h3x89** [sni/grafana-pnp-datasource#21]
Hey,
I am using Grafana (4.6.3) and some how can not connect to pnp4nagios (0.6.22-3.el7)
![image](https://user-images.githubusercontent.com/3736964/41715144-cdef8074-7552-11e8-8638-e7bb07ccf344.png)
As you can see error alert-body in empty.

I tried to look into grafana log for any information but without any results.

From grafana host, wget works correctly:
![image](https://user-images.githubusercontent.com/3736964/41715190-eddbe012-7552-11e8-8b5f-3a455cc3b7c1.png)

In additional curl to PNP api works fine:
![image](https://user-images.githubusercontent.com/3736964/41715699-9344c0d6-7554-11e8-9db5-0c9375e43035.png)

How can I debug that more?

**Comment by sni** [comment]
Have you tried updating Grafana? There is Grafana 5 meanwhile.

**Comment by h3x89** [comment]
I checked and integration with grafana 5.2.0-beta3 (latest) and all works fine but is there any possibility debug potential problems with plugin?

**Comment by sni** [comment]
we use this plugin with latest grafana without problems.
