### ISSUE TITLE
Compatibility with pnp4nagios 0.14.4

### ISSUE THREAD

**Issue by Dudssource** [sni/grafana-pnp-datasource#22]
Hi,
First of all, congratulations for the great work.
I created an alternative version of the pnp4nagios api to integrate older versions of pnp4nagios (0.14.4) with grafana-pnp-datasource.
The ideia was to use the api with the default CentOS based Nagios VM without any additional installations and also make it compatible with older versions of Nagios that are already up (upgrade the rrdtool might not be a good ideia).
The code is in my github repository:
[pnp4nagios](https://github.com/Dudssource/pnp4nagios)

I'm sharing the api here, so other people can use it too.
If you are interested or have any doubts, ideas or just a feedback, please contact me.

Hugs

**Comment by sni** [comment]
thanks for sharing :-)
