### ISSUE TITLE
Datasource "Http Error not found"

### ISSUE THREAD

**Issue by domsch1988** [sni/grafana-pnp-datasource#23]
I've just installed Grafana and can't get the pnp4nagios Datasource configured.
Grafana is running on a separate Server from Nagios. Both in the same subnet.
Grafana and pnp4nagios Installation have been done as documented.

From the Grafana Servers commandline, curl http://nagiosserver/pnp4nagios/ works correctly (Redirected page). When configuring the Datasource in Grafana, under Http - Access i only get "Server" or "Browser" as options, neither "proxy" nor "direct". Not sure why that's the case.

Grafana Version: 5.3.2
pnp4nagios Version: 0.6.26
Nagios XI Version: 5.5.2

Any help would be highly appreciated.

Edit: Logs say the following:
`t=2018-11-08T10:43:20+0100 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/3/index.php/api status=404 remote_addr=10.40.1.154 time_ms=10 size=2193 referer=http://10.90.0.73:3000/datasources/edit/3`

**Comment by sni** [comment]
server is meant to be the proxy, while browser means direct.
