### ISSUE TITLE
PNP yaml config file

### ISSUE THREAD

**Issue by gmourani** [sni/grafana-pnp-datasource#25]
Hello,

According to this Grafana link -> http://docs.grafana.org/administration/provisioning/#datasources?utm_source=grafana_ds_list , it’s possible now with Grafana version 6.0.1 to manage datasources in Grafana by adding one or more yaml config files in the provisioning/datasources directory. This is what I've tried to do for Grafana-PNP with the following config file but doesn't work and I suppose it's because Grafana-PNP is not presently supported !

# config file version
apiVersion: 1
deleteDatasources:
- name: Test
orgId: 1
datasources:
- name: Test
type: PNP
access: direct
orgId: 1
url: https://192.168.2.227/pnp4nagios
withCredentials: true
isDefault: true
editable: true

Grafana : 6.0.1
pnp4nagios : 0.6.26
Nagios : 4.3.2

**Comment by sni** [comment]
that worked in grafana 5 already and i don't see a reason why this shouldn't work with this datasource. In fact we use that in omd-labs already, see:
https://github.com/ConSol/omd/blob/labs/packages/pnp4nagios/skel/etc/pnp4nagios/grafana_datasource.yml
From a quick look, your type is wrong.

**Comment by gmourani** [comment]
Hello,

Thanks for your reply. As you said, my defined type were wrong. I've changed it for -> "sni-pnp-datasource" and now it's working.
