### ISSUE TITLE
Special characters in host or service name

### ISSUE THREAD

**Issue by McBane87** [sni/grafana-pnp-datasource#26]
Hi,

I'm having issues with a service called "disk /" when calling it directly via url variables.
In Grafana, if I select the service from a dropdown, then everything works fine, because somethings seems to convert "disk /" to "disk__" in url. But if I try to call the service directly, using the icingaweb2 module for grafana" it's not working. Because the module sends the real service name.

Could it be possible, that this module isn't escaping those names correctly for regex matches?

Example of the call:
http://127.0.0.1:3000/render/dashboard-solo/db/icinga2-default-pnp?var-hostname=Icinga2-J1900.lpz.local&var-service=disk%20%2F&var-command=disk&panelId=1&orgId=1&width=640&height=280&theme=light&from=now-6h&to=now

See attached the JSON-Code of the Dashboard I'm using for this IcingaWeb2 Module.
[icinga-default-pnp.json.txt](https://github.com/sni/grafana-pnp-datasource/files/3025677/icinga-default-pnp.json.txt)

**Comment by sni** [comment]
how is this related to this datasource? Sounds like this issue should be adressed to the icinga2 module. This datasource simply connects grafana to pnp, no icinga involved here.

**Comment by McBane87** [comment]
You didn't even read the question correctly :-(
Try the Dashboard I attached in Grafana and then access a Service with a Slash inside. For example like this:

http://127.0.0.1:3000/render/dashboard-solo/db/icinga2-default-pnp?var-hostname=<some-host>&var-service=<service with a slash>

No Icinga needed to reproduce this. I just found this issue while using Icinga.
