### ISSUE TITLE
Feature request: Grafana variables in wildcard search

### ISSUE THREAD

**Issue by joedugdale** [sni/grafana-pnp-datasource#28]
Hi

Apologies if this is already possible, what we are after after is being able to include a grafana variable in the Host search , adding to the existing wildcard search functionality.

At the moment i can choose all app servers eg /.\*app.\*/  or filter a particular env with this wildcard search

What we would like is to be able to refer to a custom grafana variable in this host search.

EG lets call the var env, with the values tsa,tsb,tsc

A host search of /^$env$.\*app.\*$/ (or similar) that would return all the app servers for the selected dropdown eg. tsa-app\* servers.

This would allow for us to have one overview dashboard instead of separate dashboards for each environment. If there's already a cunning way to do this that'd be great too.

**Comment by joedugdale** [comment]
asterisk's  didnt come through on the issue, /.*app.*/  and  /^$env$.*app.*/

**Comment by joedugdale** [comment]
This works! 
/.\*${env}esb.\*/

**Comment by sni** [comment]
thanks for the heads up
