### ISSUE TITLE
Problem Grafana

### ISSUE THREAD

**Issue by wosiek21** [sni/grafana-pnp-datasource#29]
I started using Grafana and i have problem with connect nagios to grafana. I Install Nagios, PNP4Nagios and Grafana in one sever as here https://gitlab.com/ska19/nagiosbundle
When i loggin to grafana i see PNP, i put there URL: http://localhost/pnp4nagios and i have in the screen something like: HTTP Error Internal Server Error
In /var/log/grafana/grafana.log i have: t=2020-05-13T10:57:41+0200 lvl=eror msg=“Request Completed” logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/1/index.php/api status=500 remote_addr=192.168.1.106 time_ms=7 size=2256 referer=http://192.168.1.113:3000/datasources/edit/1/

![image](https://user-images.githubusercontent.com/65304608/81844830-fabf0880-954f-11ea-91d5-6c184f752b33.png)

When i try make:
URL:http://localhost/pnp4nagios
Acces: Browser
Check Basic Auth and With Credentials
Its seems ok, but i dont have nothing here:

![image](https://user-images.githubusercontent.com/65304608/81844941-23470280-9550-11ea-8118-7489202f8533.png)

**Comment by sni** [comment]
Have you installed the pnp api extension as mentioned here in the Readme? Afaik it is still not included in the latest pnp4nagios release.

**Comment by wosiek21** [comment]
I just make: 

wget "https://github.com/lingej/pnp-metrics-api/raw/master/application/controller/api.php" \
     -O /usr/local/pnp4nagios/share/application/controllers/api.php

restart all and still have problem: 

![image](https://user-images.githubusercontent.com/65304608/81850550-6f964080-9558-11ea-91c5-2cf1aa871e92.png)

**Comment by sni** [comment]
If there is an internal server error, there should be something logged anywhere. Most probably in the apache error log

**Comment by wosiek21** [comment]
![image](https://user-images.githubusercontent.com/65304608/81851283-7ec9be00-9559-11ea-9064-b9133179e25d.png)

**Comment by wosiek21** [comment]
Meaby something is wrong here?
![image](https://user-images.githubusercontent.com/65304608/81851464-ccdec180-9559-11ea-9924-aead1144ac1f.png)

**Comment by sni** [comment]
not really helpful. You could have a look at the chrome dev tools or the firefox web developer toolbar while testing the datasource and see if there are any hints in the response.

**Comment by wosiek21** [comment]
![image](https://user-images.githubusercontent.com/65304608/81852836-ec76e980-955b-11ea-8803-82bdceac5406.png)
I found someting here

**Comment by sni** [comment]
good, thats something to fix. Just make sure the api.php has the same permissions and owner/group as the other controller php files in that folder.

**Comment by wosiek21** [comment]
Done this: 
![image](https://user-images.githubusercontent.com/65304608/81859911-3ebd0800-9566-11ea-85af-165d85dd4b95.png)

But sill have something like:

![image](https://user-images.githubusercontent.com/65304608/81859968-56948c00-9566-11ea-9df5-6ca9f810ad81.png)

**Comment by sni** [comment]
here are some curl commands to manually test the api: https://github.com/lingej/pnp-metrics-api
Make sure the api works. Thats nothing this datasource can do about it.

**Comment by wosiek21** [comment]
Meaby problem is here? 

![image](https://user-images.githubusercontent.com/65304608/81861855-2ac6d580-9569-11ea-8591-220878f54f87.png)

I will try the curls commands

**Comment by tatref** [comment]
Same issue here. I think related to SELinux. Check `/var/log/audit/audit.log`

    type=AVC msg=audit(1596038131.954:1851): avc:  denied  { getattr } for  pid=29839 comm="httpd" path="/usr/local/monitoring/addons/pnp/share/application/controllers/api.php" dev="dm-0" ino=74720090 scontext=system_u:system_r:httpd_t:s0 tcontext=unconfined_u:object_r:admin_home_t:s0 tclass=file permissive=0

**Comment by algorux** [comment]
In my case there were two roots for that problem, try to set selinux permissive (temporal solution) with

`sudo setenforce 0`

Also, y added a Require policy in `/etc/httpd/conf.d/pnp4nagios.conf` "Require host localhost"


`# SAMPLE CONFIG SNIPPETS FOR APACHE WEB SERVER

Alias /pnp4nagios "/usr/local/pnp4nagios/share"

<Directory "/usr/local/pnp4nagios/share">
        AllowOverride None
        Order allow,deny
        Allow from all
        #
        # Use the same value as defined in nagios.conf
        #
        Require host localhost
        AuthName "Nagios Access"
        AuthType Basic
        AuthUserFile /usr/local/nagios/etc/htpasswd.users
        Require valid-user
        <IfModule mod_rewrite.c>
                # Turn on URL rewriting
                RewriteEngine On
                Options symLinksIfOwnerMatch
                # Installation directory
                RewriteBase /pnp4nagios/
                # Protect application and system files from being viewed
                RewriteRule "^(?:application|modules|system)/" - [F]
                # Allow any files or directories that exist to be displayed directly
                RewriteCond "%{REQUEST_FILENAME}" !-f
                RewriteCond "%{REQUEST_FILENAME}" !-d
                # Rewrite all other URLs to index.php/URL
                RewriteRule "^.*$" "index.php/$0" [PT]
        </IfModule>
</Directory>`
