### ISSUE TITLE
[Request][Feature] Host and Service States

### ISSUE THREAD

**Issue by rockaut** [sni/grafana-pnp-datasource#3]
Is there a way to get the Host- and Service-States into Grafana? I know the Plugin is just reading the perfdata from the rrd files and the states aren't there but can you imaging a way?

As a sidenote: thank you a million times for this plugin! Nagflux is a great idea but we also need pnp/rrd and booth solutions combined produces so many problems. This plugin just solves our need for pretty and easy to change graphs and just keeping rrd in the backend.

**Comment by sni** [comment]
You're welcome. Well, the PNP api only provides performance data. Even if it had the status, it would only be the last status. How would you want to draw that into graphs?

**Comment by rockaut** [comment]
It would be great for a dashboard (SingleStat, Text, etc.) as such. As a example, a dashboard for a VM with the performance graphs and the current states (Up, Warn, ...). I know it's not directly a point for this plugin. Maybe another plugin/data-source for the Thruk-JSON API?

**Comment by sni** [comment]
Right, sounds more like a generic thruk datasource. I could offer my help when somebody want to step in, but don't have time for this right now myself.
