### ISSUE TITLE
using wildcards?

### ISSUE THREAD

**Issue by Nozlaf** [sni/grafana-pnp-datasource#30]
Thanks for making this great plugin
 i have been using it for a long time and have found its extremely easy to use and reliable
but i want to do something new and have come stuck.

I have a series of hosts which all start with ABC followed by a number
e.g.
ABC123456

i see that the plugin supports wildcards using regex ( which I openly admit i do not understand)
my understanding is that a regex to catch my hosts would be
ABC\d*
but this does not work
is this possible? 

I wanted to do a dashboard with the hosts repeating so i don't need to hardcode each host into the dashboard (there are potentially thousands)

**Comment by sni** [comment]
could you try `/ABC\d*/`? As far as i remember regular expressions in grafana have to be put in slashes to mark them as regex.

**Comment by Nozlaf** [comment]
thanks for the quick response! works perfectly
