### ISSUE TITLE
Authentication with check-mk-raw

### ISSUE THREAD

**Issue by mrobbert** [sni/grafana-pnp-datasource#31]
I am trying to use this datasource in a standalone Grafana installation (version 7.0.3) and am trying to get data out of a server that is running check-mk-raw version 1.6.0p7. 
I have installed the pnp4nagios api script on the check_mk server and I was able to get data out of it using curl, but the only way I've been able to get it to work is to use cookies with a URL that looks like this:
https://checkmk.site.com/mysite/check_mk/login.py?_origtarget=/mysite/pnp4nagios/index.php/api/hosts&_username=grafana-ciarc&_password=mypassword&_login=1

After getting the cookie I can use the normal URL to get results from the API. Is there a way I can tell this datasource how to get and use the cookie? Or is there some other setting that I'm missing?

**Comment by sni** [comment]
This datasource knows nothing about check_mk. The readme mentions two ways to authenticate. One is simple user/password the other one passes through credentials but you have to list the cookies which should be passed through. You can check with your browsers dev tools which cookies are set.

**Comment by sni** [comment]
Here is an example how this datasource can be integrated with a 3rd party authenticator. In this case its Thruk which handles the authentication and set the cookies:
https://github.com/ConSol/omd/blob/labs/packages/pnp4nagios/skel/etc/pnp4nagios/grafana_datasource.yml
