### ISSUE TITLE
transpile error

### ISSUE THREAD

**Issue by sylekta** [sni/grafana-pnp-datasource#32]
Hi Getting this error on grafana enterprise 7.0.3

Unable to dynamically transpile ES module A loader plugin needs to be configured via `SystemJS.config({ transpiler: 'transpiler-module' })`. Instantiating https://servername/grafana/public/plugins/sni-pnp-datasource/module.js Loading plugins/sni-pnp-datasource/module

**Comment by sni** [comment]
How did you install the module?

**Comment by sylekta** [comment]
Downloaded from git, extracted the zip and copied into /var/lib/grafana/plugins and then grabbed the the api.php and copied to check_mk

**Comment by sylekta** [comment]
I think it is because of this change they made https://grafana.com/docs/grafana/latest/plugins/plugin-signature-verification/
I have tried putting in their config option to allow unsigned plugins, but didnt work

**Comment by sni** [comment]
i guess its more about the recent change to remove the dist folder from the master branch. If you want to use the release from github, you need to clone/download the release branch or build the module with grunt from the master branch.
I will update the installation instructions.

**Comment by sni** [comment]
update with 9ea3934698c592ca7a9af480ca1b68463e811950
