### ISSUE TITLE
Add dashboard variable

### ISSUE THREAD

**Issue by BertaViader-zv** [sni/grafana-pnp-datasource#33]
Hey!

First of all thanks for the plugin :) 
I have a question, how can I add a variable in the grafana dashboard, every time I try, It says `No data sources found`

I want to add a variable matching different hosts. 

![image](https://user-images.githubusercontent.com/62429344/87923194-63a98c00-ca7d-11ea-966c-95240e2f3fe3.png)

Could you help me? :)

Thanks,
Berta

**Comment by BertaViader-zv** [comment]
Thanks, and sorry for the silly question:
On query I need to put $host? And then the regex pattern?

As soon I put the $host on query this errors appears:
![image](https://user-images.githubusercontent.com/62429344/87928227-c3576580-ca84-11ea-99ff-f5fd807920ad.png)

**Comment by sni** [comment]
i added an example image to the readme, it simply looks like this: https://raw.githubusercontent.com/sni/grafana-pnp-datasource/master/host_template_variables.png

**Comment by BertaViader-zv** [comment]
Thank you so much!!!
