### ISSUE TITLE
Grafana v7.3.1 (6668161a88

### ISSUE THREAD

**Issue by welj** [sni/grafana-pnp-datasource#34]
today after update to grafana v7.3.1 (6668161a88) all my data error:

PNP plugin failed
Error: Unexpected token '<' Evaluating http://*********/public/plugins/sni-pnp-datasource/module.js Loading plugins/sni-pnp-datasource/module

please fix it 👍

**Comment by welj** [comment]
its ok, just run
git clone -b release-1.0.7  https://github.com/sni/grafana-pnp-datasource.git at dir plugins!

done, solved!

**Comment by sni** [comment]
great :-)
