### ISSUE TITLE
Grafana 8.3.4 

### ISSUE THREAD

**Issue by joedugdale** [sni/grafana-pnp-datasource#37]
Upgraded to the grafana version 8.3.4 and now getting

Plugin Failed

Error: [$injector:unpr] Unknown provider: eProvider <- e https://errors.angularjs.org/1.8.2/$injector/unpr?p0=eProvider%20%3C-%20e

Has this plugin been tested ok on this version of grafana?

I have reinstalled it etc

![image](https://user-images.githubusercontent.com/13843630/153332460-13cc63b9-72ee-457d-bd10-2ca32bd1a70c.png)

![image](https://user-images.githubusercontent.com/13843630/153332565-a449b286-2186-47d7-8519-ab46885ae940.png)

**Comment by sni** [comment]
this plugin has been tested till 7.x of grafana so far, i will have a look.

**Comment by sni** [comment]
Could you please try the latest release: https://github.com/sni/grafana-pnp-datasource/releases/tag/v1.0.9

**Comment by joedugdale** [comment]
Thanks Sven - quickly tried this - the logo is working now but still hitting the same Unknown provider error above. 
![image](https://user-images.githubusercontent.com/13843630/153724421-d2fccbca-0382-4298-8545-0d419f39fb18.png)

**Comment by joedugdale** [comment]
hi @sni  - dont suppose you've had chance to have another look yet?

**Comment by sni** [comment]
oh i had many looks since then. Thing is, Angular datasources are deprecated and will no longer work with future grafana releases. So it has the be rewritten for react. And this will take some time. So don't expect anything in the next days.

**Comment by sni** [comment]
Uploaded the latest release 2.0.0 which is a complete rewrite in react. Could you please try that one?
