### ISSUE TITLE
Feature Request: Ability to use regex or wildcards on "Label" option

### ISSUE THREAD

**Issue by infraweavers** [sni/grafana-pnp-datasource#38]
Hiya,

We have quite a few graphs where we have many labels against a given service (table size within a database for example). pnp4nagios graphs all these on 1 graph (albeit with colour-issues etc), however there are situations where we'd like to be able to plot them on the same grafana graph without having to duplicate the row for each one.

A simple example we have here is Check Disk:
![image](https://user-images.githubusercontent.com/36475663/161969751-2d7d9492-0e5d-4f89-9913-ebe5fdf2c589.png)

Happy to submit a PR if you can point me in the general direction of where that would live as I couldn't really find it

**Comment by sni** [comment]
Have you tried using regex? Something like `/.*/` or `/.*free/`

**Comment by infraweavers** [comment]
Yep, I did try that; it now works like a charm so I have no idea what I did wrong before. PICNIC.
