### ISSUE TITLE
2.0.0 -> "Plugin disabled"

### ISSUE THREAD

**Issue by roflmao** [sni/grafana-pnp-datasource#40]
After installing 2.0.0:
```
"Plugin disabled
Grafana Labs checks each plugin to verify that it has a valid digital signature. While doing this, we discovered that the content of this plugin does not match its signature. We can not guarantee the trustworthy of this plugin and have therefore disabled it. We recommend you to reinstall the plugin to make sure you are running a verified version of this plugin.

Please contact your server administrator to get this resolved."
```

Looks like signing is required https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/

**Comment by sni** [comment]
How did you install the 2.0.0? The update is still in review on https://grafana.com/plugins/sni-pnp-datasource
The zip file from the releases here on github is signed and (at least in my test setup) showed up as signed plugin and worked as expected.

```
%> sha1sum sni-pnp-datasource-2.0.0.zip
52e8509c4873ebda3c4294d320a24ecc08e832dc  sni-pnp-datasource-2.0.0.zip
```

Basically i just unziped that file in the grafana plugins folder. Tested with the latest Grafana 9.1.6. Which version do you use?

**Comment by roflmao** [comment]
I just unzipped from the releases here on github:
```
grafana-cfbc97b5d-l4txm:/data/plugins$ sha1sum sni-pnp-datasource-2.0.0.zip 
52e8509c4873ebda3c4294d320a24ecc08e832dc  sni-pnp-datasource-2.0.0.zip
```
I just upgraded to grafana 9.1.6

```
grafana-cfbc97b5d-l4txm:/data/plugins$ find sni-pnp-datasource
sni-pnp-datasource
sni-pnp-datasource/datasource.js
sni-pnp-datasource/src
sni-pnp-datasource/src/img
sni-pnp-datasource/src/img/logo.svg
sni-pnp-datasource/datasource.js.map
sni-pnp-datasource/query_ctrl.js.map
sni-pnp-datasource/README.md
sni-pnp-datasource/module.js.map
sni-pnp-datasource/CHANGELOG.md
sni-pnp-datasource/LICENSE
sni-pnp-datasource/module.js
sni-pnp-datasource/MANIFEST.txt
sni-pnp-datasource/partials
sni-pnp-datasource/partials/config.html
sni-pnp-datasource/partials/query.editor.html
sni-pnp-datasource/partials/query.options.html
sni-pnp-datasource/partials/annotations.editor.html
sni-pnp-datasource/test
sni-pnp-datasource/test/datasource.js
sni-pnp-datasource/test/datasource.js.map
sni-pnp-datasource/test/query_ctrl.js.map
sni-pnp-datasource/test/module.js.map
sni-pnp-datasource/test/module.js
sni-pnp-datasource/test/query_ctrl.js
sni-pnp-datasource/plugin.json
sni-pnp-datasource/dashboards
sni-pnp-datasource/dashboards/pnp_internals.json
sni-pnp-datasource/module.js.LICENSE.txt
sni-pnp-datasource/img
sni-pnp-datasource/img/logo.svg
sni-pnp-datasource/img/screenshot.png
sni-pnp-datasource/query_ctrl.js
sni-pnp-datasource/css
sni-pnp-datasource/css/query-editor.css

**Comment by roflmao** [comment]
Seems it is some dangling data from the old version of the plugin. Got this after deleting the sni-pnp-datasource in the plugins directory:
![Screenshot-1664360927](https://user-images.githubusercontent.com/599991/192756783-63704c75-00a0-4de1-83fb-f472281dd4eb.png)

**Comment by roflmao** [comment]
Seems total restart between manual plugin install/uninstall solved the issue.

**Comment by sni** [comment]
but that's the old 1.0.8 release?

**Comment by roflmao** [comment]
Yes, this got into abit of liveblogging session. its all good now when removing the references in total and restarting between installing the plugin:

![Screenshot-1664361964](https://user-images.githubusercontent.com/599991/192760035-ebdfef93-1949-4c08-acef-dec69f71180c.png)
