### ISSUE TITLE
Cant Calculate % DISK or SWAP Free / Used with Native Nagios Plugin, PNP and Grafana

### ISSUE THREAD

**Issue by Stex1980** [sni/grafana-pnp-datasource#41]
Hi,
i've a problem to graph % swap and another parameter example disk with Grafana and PNP Datasource.
The Native Plugin check_swap in the perfdata on pnp4Nagios report this parameter:
For Disk:
<NAGIOS_SERVICEPERFDATA>/=28222MiB;107262;120670;0;**134078**</NAGIOS_SERVICEPERFDATA>
For Swap:
<NAGIOS_SERVICEPERFDATA>swap=7610MB;403;80;0;**8063**</NAGIOS_SERVICEPERFDATA>

This Value are in order with ; separator 
label=VALUE;WARNING;CRITICAL;0;**TOTAL_SIZE**

When i try to create a graph i show in label swap or disk but in type i show only AVAREGE,MIN,MAX,WARNING AND CRITICAL.

 would also need to select the "**TOTAL_SIZE**" value in the type field in order to calculate the % of use 

Can you help me?

In attach the screenshot about this "ISSUE"

![GrafanaTypeSelection](https://user-images.githubusercontent.com/114596881/192816951-40cbb626-5553-4ad4-8987-4b83dd47d16b.png)
![ExampleStatusDisk](https://user-images.githubusercontent.com/114596881/192816966-6c59dce0-1154-4607-8d8a-d1deed8c7985.JPG)

I Used:
Red Hat Enterprise Linux release 8.6
Nagios® Core™ 4.4.7
PNP4Nagios version pnp-0.6.26
sni-pnp-datasource 1.0.8 and Plugin version 9.1.6
Grafana 9.1.6

**Comment by sni** [comment]
In your case MAX would be the right choice i guess. According to
https://www.monitoring-plugins.org/doc/guidelines.html#AEN201
the syntax is `'label'=value[UOM];[warn];[crit];[min];[max]`.
There is no such thing as total_size.

**Comment by Stex1980** [comment]
I Resolve the problem.

In the api.php there are only configuration for Warning and Critical and I add it  MAX Value.

This code modify:

$perflabels[] = array(
                            "label" => arr_get($value, "NAME" ),
                            "warn"  => arr_get($value, "WARN" ),
                            "crit"  => arr_get($value, "CRIT" ),
                            "max" => arr_get($value, "MAX" )
          );

**AND this**

            foreach ( $xpd->data->row as $row=>$value){
              // timestamp in milliseconds
              $timestamp = ( $start + $i * $step ) * 1000;
              if($type == "WARNING") {
                $d = floatval($tmp_perflabel['warn']);
              } elseif($type == "CRITICAL") {
                $d = floatval($tmp_perflabel['crit']);
              } else {
                $d = floatval($tmp_perflabel['max']);
              }
              $data['targets'][$key][$hk]['datapoints'][] = array( $d, $timestamp );
              $i++;
            }




The Issue can be closed

**Comment by sni** [comment]
is this something that needs to be fixed in the api.php from pnp4nagios? If so, could you please provide a patch?
