### ISSUE TITLE
Nagios XI

### ISSUE THREAD

**Issue by jonesn** [sni/grafana-pnp-datasource#5]
Hi,

Do you have any idea where we would install the api controller on an XI installation. Is it even possible to use this datasource with a Nagios XI installation?

**Comment by sni** [comment]
Basically this datasource has nothing todo with Nagios, you need to add the API to PNP4Nagios. But i have no idea where that is for Nagios XI.

**Comment by krutaw** [comment]
@jonesn To make it work with Nagios XI, you'll have to upgrade your copy of pnp4nagios to the 0.6.xx releases.  This is not overly complicated, but not supported by Nagios.
