### ISSUE TITLE
Support Multiple Datapoints?

### ISSUE THREAD

**Issue by pyoungworth** [sni/grafana-pnp-datasource#6]
Does this support metrics will multiple datapoints?  I am looking at bringing in some metrics for various plugins which have multiple points stored? (i.e. apache stats for connections etc) and it looks like it only shows the first value in the ds regardless of what is chosen.

**Comment by sni** [comment]
This datasource supports multiple datapoints. You can either add multiple queries or use regular expression in the query itself to address multiple series.

**Comment by pyoungworth** [comment]
Maybe the issue is when dealing with spaces?  I have a plugin that I am using for check_apachestats which returns the performance data as "'Waiting for Connection'=5 'Starting Up'=0 'Reading Request'=4 'Sending Reply'=1 'Keepalive (read)'=0 'DNS Lookup'=0 'Closing Connection'=0 'Logging'=0 'Gracefully finishing'=0 'Idle cleanup'=0 'Open slot'=490 'Requests/sec'=0.1 'kB per sec'=0.4KB 'kB per Request'=3.0KB"  I can query the data via the pnp4nagios and pull our specific ds in the array.  If I attempt to access the data via the tool it finds all the appropriate labels but the data value is not accurate since it looks like it is always grabbing the first value.
Below is a node with both data points but it looks like it is only pulling the first data value for both events.

![screen shot 2017-05-02 at 2 32 38 pm](https://cloud.githubusercontent.com/assets/2495420/25633413/fbde406a-2f44-11e7-99b5-436e096a2aba.png)

**Comment by sni** [comment]
I assume you are using the latest version of the pnp-api and this datasource?

**Comment by pyoungworth** [comment]
Yes, looks like it is actually something that needs to be updated in the api.php.

Line # 236 updating the values to NAME instead of LABEL passes the right dataset.  I tested this with other data values without spaces and looks like it works as well.

```
if ( preg_match( $perflabel, arr_get($value, "LABEL" ) ) ){
                $perflabels[] =  arr_get($value, "NAME" );
              }
            }else {
              if ( $perflabel == arr_get($value, "LABEL" ) ){
                $perflabels[] = arr_get($value, "NAME" );
```

**Comment by sni** [comment]
We want to use Labels instead of Names. Names or often useless because special characters are removed, a disk check with label '/' has the name '_' which is totally useless. So we really want to have the label here. If there is a issue with spaces, we have to fix it differently.

**Comment by sni** [comment]
Should be fixed with latest builds.
