### ISSUE TITLE
Probably wrong API URL

### ISSUE THREAD

**Issue by Gregger83** [sni/grafana-pnp-datasource#60]
Dear Maintainers of this Repo,

shouldn't it be **/index.php/api/labels** rather than /index.php/api/label?

https://github.com/sni/grafana-pnp-datasource/blob/012d927c7897d7f6bd3996b9a2e6b4f001e919d8/src/datasource.ts#L224

When I try to access (in browser, GET) /index.php/api/label, I get an empty response.

When I try to access (in browser, GET) /index.php/api/labels, I get the error message, that I didn't provide POST-data (containing search parameters).

Calling  /index.php/api/labels behaves the same like /index.php/api/services and /index.php/api/hosts

Thanks for review

Kind Regards

Gregor

**Comment by sni** [comment]
Thanks, you are totally right. This needs to be `labels`. It will be fixed in the next release.
