### ISSUE TITLE
Different values from Perfdata and grafdata

### ISSUE THREAD

**Issue by c0c00n** [sni/grafana-pnp-datasource#7]
Got the following performance date from a client trough nagios and check_wmi_plus.

Status Information:	
OK (Sample Period 180 sec) - Number of Interfaces=1. Interface Details - OK - 
Interface:Embedded FlexibleLOM 1 Port 1, 
IP Address: ([IPADRESS_V4],[IPADDRESS_V6]), MAC Address [MACADDRESS], Speed:10Gbit/s, DHCPEnabled=False, 
Byte Send Rate=1.745MB/sec (Utilisation=0.14%), 
Byte Receive Rate=115.701KB/sec(Utilisation=0.01%) Packet Send Rate=1.271Kpacket/sec, 
Packet Receive Rate=372packet/sec, 
Output Queue Length=0, 
Packets Received Errors=0

Performance Data:	
'Embedded FlexibleLOM 1 Port 1 BytesSentPersec'=1744913; 
'Embedded FlexibleLOM 1 Port 1 Send Utilisation'=0.14%; 
'Embedded FlexibleLOM 1 Port 1 BytesReceivedPersec'=115701; 
'Embedded FlexibleLOM 1 Port 1 Receive Utilisation'=0.01%; 
'Embedded FlexibleLOM 1 Port 1 PacketsSentPersec'=1271; 
'Embedded FlexibleLOM 1 Port 1 PacketsReceivedPersec'=372; 
'Embedded FlexibleLOM 1 Port 1 OutputQueueLength'=0; 
'Embedded FlexibleLOM 1 Port 1 PacketsReceivedErrors'=0;

From the perfdata we see there a difference between send and receive, the same difference is see in the pnp4nagios plugin.

In Grafana the values are the same :-/ or do i miss something?

![grafana](https://cloud.githubusercontent.com/assets/13831588/26551275/fce3b538-4481-11e7-8656-f7f75fdd3c96.png)

Thanks Cocoon

**Comment by sni** [comment]
Are you using the latest version of the datasource and api?

**Comment by c0c00n** [comment]
using PNP Grafana Datasource 1.0.1 with latest api b9ebbc7 on 20 Feb

**Comment by sni** [comment]
Should be fixed with latest builds.
