### ISSUE TITLE
Pnp4Nagios doe not work with PHP 8

### ISSUE THREAD

**Issue by fabriceverkor** [sni/grafana-pnp-datasource#77]
We just migrated to Debian Bookworm which comes with PHP 8
Unfortunately, Pnp4Nagios stopped to work, and Grafana could not fetch data anymore from it.

If I understand well, The Kohana Framework used by PNp4Nagios is not  supported in PHP 8.
Do I understand well ?
Is there something to do on your Grafana plugin side ?

We use a CheckMK RAW version on which we haved maintained Pnp4Nagios WEB interface (with difficulties as they decided to delete the WEB part from OMD) sot that Grafana plugin still works.
The CheckMK plugin for Grafana does not work with host variables (https://github.com/Checkmk/grafana-checkmk-datasource/issues/247), 
So for the moment, we are stucked.

**Comment by sni** [comment]
There is nothing this datasource can do about it. It requires a working pnp backend.
However, there are pnp forks working with php 8, ex.: we maintain a fork of pnp here https://github.com/ConSol-Monitoring/pnp which is used for the omd-labs package at
https://github.com/ConSol-Monitoring/omd/tree/labs/packages/pnp4nagios
But no idea if you can get this into checkmk somehow.

**Comment by fabriceverkor** [comment]
Good news.
I had some headache to implement old Pnp4Nagios in recent CheckMK version.
I'll give a try to this fork and let you know.
Thx

**Comment by fabriceverkor** [comment]
Hello, I confirm hat your Pnp fork is working fine.
Of course, to work it in CheckMk, it needs a  /omd/<site>/etc/apache/conf.d/pnp4nagios.conf
On my side, I had to disable authentication in omd/sites/<site>/etc/pnp4nagios/config.php

$conf['auth_enabled'] = FALSE; // CHANGED BY ANSIBLE

$conf['auth_multisite_enabled'] = FALSE; // CHANGED BY ANSIBLE
