### ISSUE TITLE
Direct links to host and service

### ISSUE THREAD

**Issue by bjornfro** [sni/grafana-pnp-datasource#9]
Hi,

Not an issue but a question. Is is possible to direct link to a graph, if so how? I guess something like histou is used for which I have not yet tried.  Does histou work with grafana-pnp-datasource as well?

Sorry for maybe a stupid question but new to Grafana as well.

Regards, Bjorn

**Comment by sni** [comment]
You could use templating variables which then can be set by url parameters. There is a small description in the readme about what template variables are available.
